/** Declaration file generated by dts-gen */

export const base: string;

export const className: string;

export const ext: string;

export const size: string;

export function onerror(): void;

/**
 *
 *
 * @export
 * @param {*} what
 * @param {*} how
 * @returns {*}
 */
export function parse(what: any, how: any): any;

export function replace(text: any, callback: any): any;

export function test(text: any): any;

export namespace convert {
    function fromCodePoint(codepoint: any): any;

    function toCodePoint(unicodeSurrogates: any, sep: any): any;

    namespace fromCodePoint {
        const prototype: {
        };

    }

    namespace toCodePoint {
        const prototype: {
        };

    }

}

export namespace onerror {
    const prototype: {
    };

}

export namespace parse {
    const prototype: {
    };

}

export namespace replace {
    const prototype: {
    };

}

export namespace test {
    const prototype: {
    };

}

